### ISSUE TITLE
Can't add filters 

### ISSUE THREAD

**Issue by goomason** [tuskyapp/faq#11]
I can't add filters under Account Preferences - it gives the error "Error creating filter" on both Android 13 and Android 9 phones.

If you add filters via the Mastodon app or website they show up OK in Tusky. You can edit them, but they don't update to reflect the edit (and it can sometimes make the Tusky app close when you hit the 'update' button).

(I've had another user of the app confirm it's also happening to them).

**Comment by connyduck** [comment]
This was a bug in Mastodon that has been fixed https://github.com/mastodon/mastodon/issues/20358
