### ISSUE TITLE
Access to preferences / search from hidden header

### ISSUE THREAD

**Issue by judehansen** [tuskyapp/faq#12]
In the Android app, I inadvertently collapsed/hid the header and I can't find the way to access the flyout side menu, the preferences to reshow the header, or the search. I've been swiping and long-pressing everything I can to no avail. thanks.

**Comment by judehansen** [comment]
of course, I find it after I post this message. Long pressing on the left edge. got it. thanks.

**Comment by mal0ki** [comment]
solution found

**Comment by kawazoe** [comment]
Hey, I just wanted to point out that this happened to me too. Even knowing how to get the menu back, it was still difficult as the trigger conflicts with gesture navigation on my phone.

I think a great solution would be to support having the account menu in the tab bar, and add it automatically when turning on this feature. It would prevent accidents.
