### ISSUE TITLE
Cannot access pleroma.site API

### ISSUE THREAD

**Issue by shuuji3** [tuskyapp/faq#14]
In the answer about maximum character limit, there is a link to https://pleroma.site/api/v1/instance. But it looks like this site is not running now.

**Comment by mal0ki** [comment]
Yeh, it's not been updated in a while. We'll fix.

**Comment by shuuji3** [comment]
OK, understand🙂 Thank you for the effort.

**Comment by connyduck** [comment]
Faqs no longer include the url
