### ISSUE TITLE
Enlarging the button boundaries.

### ISSUE THREAD

**Issue by BloomyJaz** [tuskyapp/faq#18]
![Screenshot_20230102_120823_Tusky](https://user-images.githubusercontent.com/89125709/210270667-79c0a557-1763-46dd-8b9d-1ca5420cce5b.png)
While skimming through content and favouriting lots of posts it is extremely easy to miss the button bounds and accidentally expand the post which can be irritating.

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/2872
