### ISSUE TITLE
Timelines loading additional toots

### ISSUE THREAD

**Issue by itsmejabu** [tuskyapp/faq#19]
hi all, 
after a certain number of new toots while being absent the timelines show a button named <<load more>> (or similar). When pressing, additional toots are showed. My issue is, that these toots are showed below actual position, what means that user needs to read from newer to older what makes no sense from my point of view. Alternatively user needs to scroll down and find manually their last position in timeline, to be able to read from older to newer (what would be the 'normal' way.
So, instead of showing additional toots below actual position they should be displayed obove?
Ceers, Jan

**Comment by connyduck** [comment]
This will be addressed in Tusky 21 with a new setting
