### ISSUE TITLE
prerequisites for having emoji support in tusky

### ISSUE THREAD

**Issue by TheOtherDoctor** [tuskyapp/faq#5]
When I lately got my first dvice equipped with an Android 10 based OS (having only Android 7 based before), for the first time I had the emoji button in tusky functional. On previous systems the button was greyed out and did - nothing. As I understand emoji support is provided by the OS and tusky (in contrast to WhatsApp and other apps who implement their own emoji sets) relies on those; I wonder if this is an FAQ topic to get info on which prerequisite to fulfill in order to get emojis working in tusky. In the unlikely case this is a new observation, I can of course put this into a regular issue for the app.

**Comment by connyduck** [comment]
Have you switched to another instance? The emojis in Tusky are not the Android system emojis (for those you have to use your keyboard) but the custom emojis provided by the instance. Or maybe your admin has only recently added some?
